### ISSUE TITLE
Deps Check Unused Check

### ISSUE THREAD

**Issue by asummers** [karolsluszniak/ex_check#17]
Elixir 1.10 added a new useful check. While this can obviously be accomplished with the addition of

```
    {:unused_deps, command: "mix deps.unlock --check-unused"},
```

in `.check.exs`, what is the plan for doing checks that are built into the language based on the language version? Would this be something you'd want to see in `ex_check`?

**Comment by karolsluszniak** [comment]
Cool. I was not aware of this task. It looks like a worthwhile additon to curated tools, since it’s easy to forget about dropped deps.

We’d have to add another type of *:detect* and define the tool with that in default config. It could be *{:elixir, >= 1.10.0}* using *Version* module for resolving the condition.

**Comment by asummers** [comment]
Such a version detect opt could be useful to retrofit language versions and be able to compile this for older elixir versions that don't have formatter, if that was something you were interested in.

**Comment by karolsluszniak** [comment]
Sure, although I'm not sure it's worth the effort, i.e. if there's a demand among users of such old Elixir versions. If so, I'll gladly accept such a contribution.
