### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by manuel-rubio** [karolsluszniak/ex_check#32]
Could it be possible to have a check also for the test coverage? It could be great to have even the configuration to know if that should be appearing in green or red based on the percentage.

**Comment by karolsluszniak** [comment]
Hey. I've explored this idea and even coded a separate tool for this exact purpose - feel free to check it out at [ex_uncov](https://github.com/karolsluszniak/ex_uncov) repo. Still, I'm not 100% convinced as to whether it's worth it to face all the consequences of managing coverage tracking in version control (and that's the only way it could work with tool like ex_check) due to conflicts, extra fuss etc. I haven't tried it in any real project so far but fee free to do so if you see it helpful.

Closing for now. I'm assuming we can move any specific discussions to that repo instead.
