### ISSUE TITLE
Feature request – retry everything

### ISSUE THREAD

**Issue by lud-wj** [karolsluszniak/ex_check#40]
Currently the retry option will only run what failed, which is useful for random failures.

But I have another use case. I follow the following coding process:

* write a test
* implement a solution quickly until the test is green
* refactor a bit
* loop

I never check for formatting, credo stuff, or dialyzer problems at every loop, that would be too slow. I like to do there every N loops depending on what I am implementing.

So generally when I run mix check is before commit, once everything is green and I have a complete thing working. So in general I'll have several checks that fail ; most of the time the formatter, credo and some compiler warnings.

So I would like `mix check` to write in its state that 3 checks are failing. And then, when I run it again, it will only retry what failed (the current behaviour) until all the previously failing checks are now green. At this point I would like mix check to re-run everything (except those it just ran in the same CLI call that were green for the first time) to be sure that I did not make another check fail when fixing one of the 3. If everything is green, then the state is reset and I will run everything anew.

Some example of successive calls to `mix check`

1. runs everything, credo and formatter are red.
1. runs only credo and formatter, still red
1. runs only credo and formatter, now formatter is green and credo red
1. runs only credo, credo is green so it runs also everything except credo (because it happens in the same command 
 call), dialyzer is now red, oops.
1. runs only diyalizer, dialyzer is green, so it runs everything else, everything is green.
1. runs everything …

What do you think?

To not mess with people CI configs it could be another option, `incremental_retry` that would turn on this behaviour. If `retry` is also true, `incremental_retry` would take precedence.

**Comment by karolsluszniak** [comment]
ExCheck currently enables retry mode when some checks have failed and carries on in this mode until all those failed checks are successful (running only these failed checks until they’re all successful). Then it runs all checks again. So that’s the only difference in its behaviour vs what was described above - ExCheck does not remember which tools were ran in last retry run in order to cut on running them in next full run. And IMO it should stay this way. Why? Because tools that are ran in retry mode may (and in case of ExUnit do via —failed arg) also run only their last failed subset of checks. So when I want a final run to validate everything „one last tine” after the fix-n-retry round, I want to run it all, no dependence on any prior incomplete retry run.

Please also note that the manifest file used by retry mode is documented and available for custom tooling so if you’re set on implementing your custom flow, you can just do without this being part of ExCheck itself.

**Comment by lud-wj** [comment]
> ExCheck currently enables retry mode when some checks have failed and carries on in this mode until all those failed checks are successful (running only these failed checks until they’re all successful). Then it runs all checks again.

This is not my experience. With `retry: true` in the config, `mix check` only runs the compiler task.

```
[
  parallel: true,
  skipped: false,
  fix: false,
  retry: true,
  tools: [
    {:compiler, true},
    {:doctor, false},
    {:gettext, false},
    {:credo, "mix credo --all --strict"},
    # custom audit command
    {:"deps.audit", "mix deps.audit --format human"},
    {:mix_audit, false}
  ]
]
```

Even without failing anything before, `mix check` will not run anything besides the compiler. I don't know why but it's kind of the opposite of what I expect from such a tool. If I execute `mix check`, it is supposed to check stuff without additional flags.

If I understand correctly, once you add `retry: true` in the config, you are supposed to pass the `--no-retry` flag everytime you want to actually check your code, is that right?
